LayoutsMVC/Controllers/EMPController.cs
using LayoutsMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutsMVC.Controllers
{
    public class EMPController : Controller
    {
        // GET: EMP
        public ActionResult Index()
        {
            List<EMPDATA> l = LayoutOperations.Getall();
            return View(l);
        }
        public ActionResult create()
        {
           
          
            return View();
        }
       
        public ActionResult createrecord(EMPDATA e)
        {
            ViewBag.msg = LayoutOperations.InsertEMPDATA(e);
            return View("create");
        }
       


        public ActionResult edit(int id)
        {
            EMPDATA emp = LayoutOperations.emp_edit(id);
            return View(emp);

            
        }
        public ActionResult extract_edit(EMPDATA e)
        {
            int empno = int.Parse(Request.Form["EMPNO"]);
            string s = LayoutOperations.editbtn(empno, e);
            ViewBag.msg = s;
            return View("edit");



        }
        public ActionResult delete_emp(int id)
        {
          
            LayoutOperations.empno_del(id);
            return RedirectToAction("Index");
        }

    }
}

LayoutsMVC/Views/EMP/Index.cshtml
@model IEnumerable<LayoutsMVC.Models.EMPDATA>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MasterLayoutpage.cshtml";
}

<h2>Index</h2>

<p>@Html.ActionLink("Create New","create","EMP")</p>
@using (Html.BeginForm())
{
    if (Model != null)
    {
<table>
    <tr>
        <td>Empno</td>
        <td>Ename</td>
        <td>Job</td>
        <td>MGR</td>
        <td>Hiredate</td>
        <td>Sal</td>
        <td>Comm</td>
        <td>Deptno</td>
    </tr>
    @foreach (var i in Model)
    {
        <tr>
            <td>@i.EMPNO</td>
            <td>@i.ENAME</td>
            <td>@i.JOB</td>
            <td>@i.MGR</td>
            <td>@i.HIREDATE</td>
            <td>@i.SAL</td>
            <td>@i.COMM</td>
            <td>@i.DEPTNO</td>
            <td>@Html.ActionLink("Edit", "edit", "EMP", new { id = i.EMPNO }, null)</td>
            <td>@Html.ActionLink("Delete", "delete_emp", "EMP", new { id = i.EMPNO }, null)</td>

        </tr>



    }


</table>


    }

}

LayoutsMVC/Views/EMP/create.cshtml
@model LayoutsMVC.Models.EMPDATA
@{
    ViewBag.Title = "create";
    Layout = "~/Views/Shared/_MasterLayoutpage.cshtml";
}

<h2>create</h2>

@using (Html.BeginForm("createrecord","EMP"))
{
    <table>
        <tr>
            <td>Empno</td>
            <td>@Html.TextBoxFor(a => a.EMPNO)</td>
        </tr>
        <tr>
            <td>Ename</td>
            <td>@Html.TextBoxFor(a => a.ENAME)</td>
        </tr>
        <tr>
            <td>Job</td>
            <td>@Html.TextBoxFor(a => a.JOB)</td>
        </tr>
        <tr>
            <td>MGR</td>
            <td>@Html.TextBoxFor(a => a.MGR)</td>
        </tr>
        <tr>
            <td>Hiredate</td>
            <td>@Html.TextBoxFor(a => a.HIREDATE)</td>
        </tr>
        <tr>
            <td>Sal</td>
            <td>@Html.TextBoxFor(a => a.SAL)</td>
        </tr>
        <tr>
            <td>Comm</td>
            <td>@Html.TextBoxFor(a => a.COMM)</td>
        </tr>
        <tr>
            <td>Deptno</td>
            <td>@Html.TextBoxFor(a => a.DEPTNO)</td>
        </tr>
        <tr>
            <td><input type="submit" value="insert" /></td>
        </tr>



    </table>
    if (ViewBag.msg != null)
    {
        <h2> @ViewBag.msg</h2>
    }
}
<div>
    @Html.ActionLink("Back to List", "Index");
</div>

LayoutsMVC/Views/EMP/delete.cshtml
@{
    ViewBag.Title = "delete";
}

<h2>delete</h2>

LayoutsMVC/Views/EMP/delete_emp.cshtml
@{
    ViewBag.Title = "delete_emp";
}
<h2>DELETION DONE</h2>
<div>
    @Html.ActionLink("Back to list", "Index", "EMP");
</div>

LayoutsMVC/Views/EMP/edit.cshtml
@model LayoutsMVC.Models.EMPDATA
@{
    ViewBag.Title = "edit";
}

<h2>edit</h2>
@using (Html.BeginForm("extract_edit", "EMP"))
{
   
        <table>
            <tr>
                <td>Empno</td>
                <td>@Html.TextBoxFor(a => a.EMPNO)</td>
            </tr>
            <tr>
                <td>Ename</td>
                <td>@Html.TextBoxFor(a => a.ENAME)</td>
            </tr>
            <tr>
                <td>Job</td>
                <td>@Html.TextBoxFor(a => a.JOB)</td>
            </tr>
            <tr>
                <td>MGR</td>
                <td>@Html.TextBoxFor(a => a.MGR)</td>
            </tr>
            <tr>
                <td>Hiredate</td>
                <td>@Html.TextBoxFor(a => a.HIREDATE)</td>
            </tr>
            <tr>
                <td>SAL</td>
                <td>@Html.TextBoxFor(a => a.SAL)</td>
            </tr>
            <tr>
                <td>Comm</td>
                <td>@Html.TextBoxFor(a => a.COMM)</td>
            </tr>
            <tr>
                <td>deptno</td>
                <td>@Html.TextBoxFor(a => a.DEPTNO)</td>
            </tr>

            <tr>
                <td><input type="submit" value="EDIT" /></td>
            </tr>








        </table>
        if (ViewBag.msg != null)
        {
            <h2> @ViewBag.msg</h2>
        }


    
}
<div>
    @Html.ActionLink("Back to List", "Index");
</div>