LayoutsMVC/Controllers/CheckboxController.cs
using LayoutsMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutsMVC.Controllers
{
    public class CheckboxController : Controller
    {
        // GET: Checkbox
        List<EMPDATA> l = null;
        public ActionResult Viewdetails()
        {
            l = LayoutOperations.Getall();

            ViewBag.emplist = l;
            return View();
        }
        public ActionResult chckboxextract()
        {
          var e = Request.Form.Get("chckbox");
            l = LayoutOperations.Getall();
            List<EMPDATA> newlist = new List<EMPDATA>();
            foreach(var item in l)
            {
                if (e.Contains(item.EMPNO.ToString()))
                {
                    newlist.Add(item);
                }

            }
          
            return View(newlist);


        }
    }
}

LayoutsMVC/Views/Checkbox/Viewdetails.cshtml
@{
    ViewBag.Title = "Viewdetails";
     Layout = "~/Views/Shared/_MasterLayoutpage.cshtml";
}

@using (Html.BeginForm("chckboxextract","Checkbox"))
{
    <table border="1">
        <tr>
            <td>EMPNO</td>
            <td>ENAME</td>
            <td>JOB</td>
            <td>MGR</td>
            <td>HIREDATE</td>
            <td>SAL</td>
            <td>COMM</td>
            <td>DEPTNO</td>
            <td><input type="submit" value="submit" /></td>
        </tr>

        @foreach (var i in ViewBag.emplist as IList<LayoutsMVC.Models.EMPDATA>)
        {
    <tr>

        <td>@i.EMPNO</td>
        <td>@i.ENAME</td>
        <td>@i.JOB</td>
        <td>@i.MGR</td>
        <td>@i.HIREDATE</td>
        <td>@i.SAL</td>
        <td>@i.COMM</td>
        <td>@i.DEPTNO</td>
        <td>@Html.CheckBox("chckbox", new { @value=i.EMPNO })</td>

    </tr>

        }


    </table>



}

LayoutsMVC/Views/Checkbox/chckboxextract.cshtml
@model IEnumerable<LayoutsMVC.Models.EMPDATA>
@{
    ViewBag.Title = "chckboxextract";
}

@using (Html.BeginForm())
{
    if (Model != null)
    {
    <table border="1">
        <tr>
            <td>EMPNO</td>
            <td>ENAME</td>
            <td>JOB</td>
            <td>MGR</td>
            <td>HIREDATE</td>
            <td>SAL</td>
            <td>COMM</td>
            <td>DEPTNO</td>
            </tr>




            @foreach (var i in Model)
            {
            <tr>

                <td>@i.EMPNO</td>
                <td>@i.ENAME</td>
                <td>@i.JOB</td>
                <td>@i.MGR</td>
                <td>@i.HIREDATE</td>
                <td>@i.SAL</td>
                <td>@i.COMM</td>
                <td>@i.DEPTNO</td>

            </tr>





        }
        </table>
    }
}