LayoutsMVC/Controllers/BindingController.cs
using LayoutsMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayoutsMVC.Controllers
{
    public class BindingController : Controller
    {
        // GET: Binding
        [ActionName("Example")]//for the end user it will show while running as "Example" 
        public ActionResult Sample()
        {
            return View("Sample");//when using actionname, we have to specify methodname in view.
        }
        public ActionResult Index_bind()
        {
            return View();
        }
        public ActionResult Update_Bind(int id)//always use id because it represents the primary key in that table
        {


            return View("Index_bind",LayoutOperations.emp_edit(id));
        }
        //[HttpPost]
        //public ActionResult Update_Bind(EMPDATA e)//receiving object using bind-called as complex binding
        //{

        //    return View();
        //}
        //[HttpPost]
        //public ActionResult Update_Bind(FormCollection f)
        //{
        //    int eno = int.Parse(f["EMPNO"]);
        //    string ename = f["ENAME"];
        //    return View();


        //}
        [HttpPost]
        public ActionResult Update_Bind([Bind(Include="EMPNO,ENAME")]EMPDATA e)
        {

            return View();
        }
       
     


    }
}

LayoutsMVC/Views/Binding/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

LayoutsMVC/Views/Binding/Index_bind.cshtml
@model LayoutsMVC.Models.EMPDATA
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_MasterLayoutpage.cshtml";
}
    <script src="~/Scripts/updatejs.js"></script>
<h2>INDEX</h2>

@using (Html.BeginForm("Update_Bind","Binding"))
{
    <table>
        <tr>
            <td>Empno</td>
            <td>@Html.TextBoxFor(a => a.EMPNO,"",new { onblur="func1();"})</td>
        </tr>
        <tr>
            <td>Ename</td>
            <td>@Html.TextBoxFor(a => a.ENAME)</td>
        </tr>
        <tr>
            <td>Job</td>
            <td>@Html.TextBoxFor(a => a.JOB)</td>
        </tr>
        <tr>
            <td>MGR</td>
            <td>@Html.TextBoxFor(a => a.MGR)</td>
        </tr>
        <tr>
            <td>Hiredate</td>
            <td>@Html.TextBoxFor(a => a.HIREDATE)</td>
        </tr>
        <tr>
            <td>Sal</td>
            <td>@Html.TextBoxFor(a => a.SAL)</td>
        </tr>
        <tr>
            <td>Comm</td>
            <td>@Html.TextBoxFor(a => a.COMM)</td>
        </tr>
        <tr>
            <td>Deptno</td>
            <td>@Html.TextBoxFor(a => a.DEPTNO)</td>
        </tr>
        <tr>
            <td><input type="submit" value="insert" /></td>
        </tr>



    </table>
    if (ViewBag.msg != null)
    {
        <h2> @ViewBag.msg</h2>
    }



}

LayoutsMVC/Views/Binding/Update_Bind.cshtml
@model LayoutsMVC.Models.EMPDATA
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_MasterLayoutpage.cshtml";
}
<h2>UPDATE</h2>

@using (Html.BeginForm())
{
    <table>
        <tr>
            <td>Empno</td>
            <td>@Html.TextBoxFor(a => a.EMPNO)</td>
        </tr>
        <tr>
            <td>Ename</td>
            <td>@Html.TextBoxFor(a => a.ENAME)</td>
        </tr>
        <tr>
            <td>Job</td>
            <td>@Html.TextBoxFor(a => a.JOB)</td>
        </tr>
        <tr>
            <td>MGR</td>
            <td>@Html.TextBoxFor(a => a.MGR)</td>
        </tr>
        <tr>
            <td>Hiredate</td>
            <td>@Html.TextBoxFor(a => a.HIREDATE)</td>
        </tr>
        <tr>
            <td>Sal</td>
            <td>@Html.TextBoxFor(a => a.SAL)</td>
        </tr>
        <tr>
            <td>Comm</td>
            <td>@Html.TextBoxFor(a => a.COMM)</td>
        </tr>
        <tr>
            <td>Deptno</td>
            <td>@Html.TextBoxFor(a => a.DEPTNO)</td>
        </tr>
        <tr>
            <td><input type="submit" value="insert" /></td>
        </tr>



    </table>
    if (ViewBag.msg != null)
    {
        <h2> @ViewBag.msg</h2>
    }



}